# **06. Optional Multilingual Transformer-Embedding Benchmark**

This notebook adds a time-permitting benchmark for AT3. It compares the current TF-IDF supervised NLP pipeline with a multilingual transformer embedding representation followed by a simple supervised classifier. It is not required for the Streamlit demo and does not replace the final Linear SVM app model.

# **1. Environment Setup**

In [1]:
# Import libraries and project helper functions.
from pathlib import Path

import pandas as pd

from customer_support_ai.config import RESULTS_DIR
from customer_support_ai.transformer_benchmark import (
    DEFAULT_EMBEDDING_MODEL,
    OUTPUT_CSV,
    run_benchmark,
)

print('Embedding model:', DEFAULT_EMBEDDING_MODEL)
print('Benchmark output:', OUTPUT_CSV)

Embedding model: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Benchmark output: /Users/mariorubiano/Library/CloudStorage/OneDrive-Personal/Documents/UTS/Semester 4/AI/Assignments/AT3/trn-uts-aipa/results/transformer_embedding_benchmark.csv

# **2. Benchmark Purpose**

The baseline and comparison models in the main pipeline all use the same main paradigm: supervised NLP text classification with TF-IDF features. This optional benchmark adds a different representation approach: dense semantic multilingual transformer embeddings. The classifier is still supervised, but the language representation is transformer-based rather than sparse lexical TF-IDF.

# **3. Run Sampled Transformer Benchmark**

The benchmark uses a small language-balanced sample by default so it can run on a laptop. Increase `sample_size` only if time and compute allow it. Results should be compared cautiously against the full-data TF-IDF results because this is a sampled experiment.

In [2]:
# Run the optional benchmark. Install optional dependencies first if needed:
#   python -m pip install -r requirements-transformer.txt

benchmark_results = run_benchmark(sample_size=2500)
benchmark_results

/Users/mariorubiano/Library/CloudStorage/OneDrive-Personal/Documents/UTS/Semester 4/AI/Assignments/AT3/trn-uts-aipa/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 8453.95it/s]

Batches:   0%|          | 0/40 [00:00<?, ?it/s]

Batches:   2%|▎         | 1/40 [00:00<00:15,  2.57it/s]

Batches:   5%|▌         | 2/40 [00:00<00:12,  3.04it/s]

Batches:   8%|▊         | 3/40 [00:00<00:11,  3.30it/s]

Batches:  10%|█         | 4/40 [00:01<00:10,  3.41it/s]

Batches:  12%|█▎        | 5/40 [00:01<00:10,  3.47it/s]

Batches:  15%|█▌        | 6/40 [00:01<00:09,  3.51it/s]

Batches:  18%|█▊        | 7/40 [00:02<00:09,  3.39it/s]

Batches:  20%|██        | 8/40 [00:02<00:09,  3.42it/s]

Batches:  22%|██▎       | 9/40 [00:02<00:09,  3.44it/s]

Batches:  25%|██▌       | 10/40 [00:02<00:08,  3.47it/s]

Batches:  28%|██▊       | 11/40 [00:03<00:08,  3.50it/s]

Batches:  30%|███       | 12/40 [00:03<00:07,  3.50it/s]

Batches:  32%|███▎      | 13/40 [00:03<00:07,  3.53it/s]

Batches:  35%|███▌      | 14/40 [00:04<00:07,  3.55it/s]

Batches:  38%|███▊      | 15/40 [00:04<00:07,  3.55it/s]

Batches:  40%|████      | 16/40 [00:04<00:06,  3.56it/s]

Batches:  42%|████▎     | 17/40 [00:04<00:06,  3.47it/s]

Batches:  45%|████▌     | 18/40 [00:05<00:06,  3.55it/s]

Batches:  48%|████▊     | 19/40 [00:05<00:05,  3.53it/s]

Batches:  50%|█████     | 20/40 [00:05<00:05,  3.52it/s]

Batches:  52%|█████▎    | 21/40 [00:06<00:05,  3.56it/s]

Batches:  55%|█████▌    | 22/40 [00:06<00:04,  3.67it/s]

Batches:  57%|█████▊    | 23/40 [00:06<00:04,  3.83it/s]

Batches:  60%|██████    | 24/40 [00:06<00:04,  3.89it/s]

Batches:  62%|██████▎   | 25/40 [00:07<00:03,  4.12it/s]

Batches:  65%|██████▌   | 26/40 [00:07<00:03,  4.38it/s]

Batches:  68%|██████▊   | 27/40 [00:07<00:02,  4.58it/s]

Batches:  70%|███████   | 28/40 [00:07<00:02,  4.80it/s]

Batches:  72%|███████▎  | 29/40 [00:07<00:02,  5.08it/s]

Batches:  75%|███████▌  | 30/40 [00:07<00:01,  5.44it/s]

Batches:  78%|███████▊  | 31/40 [00:08<00:01,  5.59it/s]

Batches:  80%|████████  | 32/40 [00:08<00:01,  5.74it/s]

Batches:  82%|████████▎ | 33/40 [00:08<00:01,  6.13it/s]

Batches:  85%|████████▌ | 34/40 [00:08<00:00,  6.62it/s]

Batches:  88%|████████▊ | 35/40 [00:08<00:00,  7.05it/s]

Batches:  92%|█████████▎| 37/40 [00:08<00:00,  8.19it/s]

Batches:  98%|█████████▊| 39/40 [00:08<00:00,  9.68it/s]

Batches: 100%|██████████| 40/40 [00:08<00:00,  4.45it/s]

,task,model,split,accuracy,macro_precision,macro_recall,macro_f1,weighted_f1
0,category,transformer_embeddings_logistic_regression,sampled_test,0.272000,0.249231,0.293490,0.234789,0.290298
1,priority,transformer_embeddings_logistic_regression,sampled_test,0.357333,0.359337,0.359076,0.349574,0.364143

# **4. Compare With Current TF-IDF Results**

In [3]:
# Load the current full-data TF-IDF model results and compare headline macro F1 values.
tfidf_results = pd.read_csv(RESULTS_DIR / 'metrics_summary.csv')
tfidf_test = tfidf_results[tfidf_results['split'] == 'test'][['task', 'model', 'split', 'macro_f1', 'accuracy']]

comparison = pd.concat(
    [
        tfidf_test.assign(source='Full-data TF-IDF pipeline'),
        benchmark_results[['task', 'model', 'split', 'macro_f1', 'accuracy']].assign(source='Sampled transformer benchmark'),
    ],
    ignore_index=True,
)
comparison.sort_values(['task', 'source', 'macro_f1'], ascending=[True, True, False])

,task,model,split,macro_f1,accuracy,source
0,category,linear_svm,test,0.524646,0.530714,Full-data TF-IDF pipeline
2,category,transformer_embeddings_logistic_regression,sampled_test,0.234789,0.272000,Sampled transformer benchmark
1,priority,linear_svm,test,0.567824,0.580849,Full-data TF-IDF pipeline
3,priority,transformer_embeddings_logistic_regression,sampled_test,0.349574,0.357333,Sampled transformer benchmark

# **5. Interpretation for AT3**

Use this benchmark carefully in the final report. The current Streamlit app still uses the selected TF-IDF + Linear SVM models because they are lightweight, explainable, and already integrated. The transformer benchmark is useful as evidence of a time-permitting alternative AI approach: semantic multilingual representation. For the presentation, mention it only as future work unless the benchmark has been run and reviewed by the group.

In [4]:
# Save a concise sentence that can be reused in the final report.
summary = (
    'Optional transformer benchmark: compare sparse lexical TF-IDF features against '
    'dense multilingual transformer embeddings followed by a simple supervised classifier. '
    'This strengthens the discussion of alternative NLP paradigms without changing the demo app.'
)
print(summary)

Optional transformer benchmark: compare sparse lexical TF-IDF features against dense multilingual transformer embeddings followed by a simple supervised classifier. This strengthens the discussion of alternative NLP paradigms without changing the demo app.